[tools]
rojo = "UpliftGames/rojo@7.4.0-uplift.syncback.rc.14" # using rojo by uplift in my workflow in "main" --> other repo
selene = "Kampfkarren/selene@0.26.1"
stylua = "JohnnyMorganz/stylua@0.18.2"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
